[tool.poetry]
name = "gitreturn"
version = "1.3.1"
description = "Script to return to staging."
license = "MIT"
authors = ["blackboardd <brightenqtompkins@gmail.com>"]

[tool.poetry.scripts]
git_return = "gitreturn.cli:run"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
inquirerpy = "^0.3.3"
