[project]
authors = [
    { name = "Monkeytale", email = "monkeytale@dwlib.com" },
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.0.0",
]
name = "monkeytale"
version = "0.2.9"
description = "An opinionated markup language for composing, documenting, and visualizing a novel."
readme = "README.md"
keywords = [
    "novel",
    "structure",
    "composition",
    "documentation",
    "visualization",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Programming Language :: Python :: 3.10",
    "Topic :: Documentation",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing",
]

[project.license]
text = "Unlicense"

[project.urls]
homepage = "https://github.com/MLAOPDX/monkeytale/"
repository = "https://github.com/MLAOPDX/monkeytale/"
changelog = "https://github.com/MLAOPDX/monkeytale/blob/main/CHANGELOG.md"

[project.scripts]
"@" = "monkeytale.__init__:cli"
monkeytale = "monkeytale.__init__:cli"

[project.optional-dependencies]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = [
    "monkeytale",
]

[tool.pdm.dev-dependencies]
format = [
    "black[jupyter]>=22.3.0",
    "isort>=5.10.1",
]
test = [
    "bandit>=1.7.4",
    "devtools>=0.8.0",
    "hypothesis>=6.46.1",
    "hypothesis-faker>=0.0.23",
    "pytest>=7.1.2",
    "pytest-cov>=3.0.0",
    "setuptools>=62.3.2",
]
jupyter = [
    "jupyter>=1.0.0",
]

[tool.semantic_release]
branch = "main"
build_command = "pip install --user pdm && pdm build"
major_on_zero = false
repository = "testpypi"
upload_to_release = true
upload_to_repository = true
version_pattern = [
    "README.md:# Monkeytale v{version}",
]
version_variable = [
    "monkeytale/__init__.py:__version__",
    "pyproject.toml:version",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ignore=__pypackages__ --hypothesis-show-statistics --cov-report xml:tests/cov.xml --cov=monkeytale -ra"
testpaths = [
    "tests",
]

[tool.black]
target-version = [
    "py310",
]
experimental-string-processing = true
safe = true
