[tool.poetry]
name = "twts"
version = "0.1.1"
description = "stream tweets from the terminal"
authors = ["redraw <redraw@sdf.org>"]

[tool.poetry.scripts]
twts = "twts.stream:cli"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
tweepy = "^4.10.0"
Shapely = "^1.8.2"

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"
ipdb = "^0.13.9"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
