[tool.poetry]
name = "captif_db"
version = "0.12"
description = ""
license = "MIT"
authors = ["John Bull <john.bull@nzta.govt.nz>"]
readme = "README.md"
keywords = ["CAPTIF"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.19.1"
pandas = "^1.1.0"
toml = "^0.10.1"
schema = "^0.7.2"
mysqlclient = "^2.0.3"
captif-db-config = "0.10"
captif-data-structures = "^0.12"
captif-slp = "^0.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.0"
pre-commit = "^2.6.0"
pytest-randomly = "^3.4.1"
alembic = "^1.4.2"
sphinx = "^3.2.1"
sphinx-rtd-theme = "^0.5.0"
eralchemy = "1.2.10"
boto3 = "^1.16.30"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
