[tool.poetry]
name = "arcl"
version = "1.7.1"
description = "The CLI for Archimedes"
authors = ["Optimeering AS <dev@optimeering.com>"]
license = "Apache-2.0"
packages = [{include = "arcl"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
click = "^8.1.3"
cookiecutter = "^1.7.3"
requests = "*"
msal = ">=1.10.0,<2.0.0"
msal-extensions = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "*"
pyinstaller = "^5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arcl = "arcl.cli:cli"
