[tool.poetry]
name = "ptorru-matmul"
version = "0.1.1"
description = "Learning how to publish in PyPi through a generic implementation of matrix multiplication"
authors = ["Pedro Torruella"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ptorru/ptorru-matmul"
repository = "https://github.com/ptorru/ptorru-matmul"
documentation = "https://github.com/ptorru/ptorru-matmul/blob/main/README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
